### PR TITLE
MANTA-4629 add Jenkinsfiles to Manta repositories

### PR DESCRIPTION
**Pull request by cburroughs**

### CODE REVIEW

**Comment by trentm** [comment]
`make test` is just in a sorry state because this is all ancient. The nodeunit is ancient and has this tap dep: `    "tap": ">=0.2.3"` which results in it installing the *latest* node-tap, which only works with node 8 and above at this point, I think.   ... this is all when attempting to test with node 0.10.

I could theoretically fix up these tests to use a modernish node-tap, but I'm not sure it is worth it. This module is only used by manta-madtom. madtom currently uses node 0.10.48. I'm not sure how important, if at all, madtom is, and probably not right now.

@timfoster Thoughts here? We could just drop the 'make test' parts of this and limit to 'make check'.

**Comment by timfoster** [comment]
Yes, I'd be inclined to drop test as well, having spent a bit trying to hack around the limitations here, notably by forcing us to the minimum allowed tap:

```

timf@jenkins-agent-i386-1.6.3 (pipeline) git diff
diff --git a/Makefile b/Makefile
index c6777be..5c0c70e 100644
--- a/Makefile
+++ b/Makefile
@@ -15,7 +15,7 @@
 #
 # Tools
 #
-NPM                    := $(shell which npm)
+NPM                    := $(shell which node) $(shell which npm)
 NODEUNIT               := ./node_modules/.bin/nodeunit

 #
diff --git a/package.json b/package.json
index e01b90e..864ed17 100644
--- a/package.json
+++ b/package.json
@@ -13,7 +13,8 @@
                 "vasync": "1.3.3"
         },
         "devDependencies": {
-                "nodeunit": "0.7.4"
+                "nodeunit": "0.7.4",
+                "tap": "0.2.3"
         },
         "engines": {
                 "node": "0.8.18"
timf@jenkins-agent-i386-1.6.3 (pipeline)
```

which initially looked promising, but then showed that we're only prolonging the agony:

```
timf@jenkins-agent-i386-1.6.3 (pipeline) make check test
deps/javascriptlint/build/install/jsl --nologo --nosummary --conf=tools/jsl.node.conf lib/index.js lib/health_checker.js lib/checkers/noop_checker.js lib/checkers/dns_checker.js lib/checkers/http_checker.js lib/checkers/tcp_checker.js lib/checkers/checker.js lib/all_checkers.js lib/hc_server.js lib/time_bucket.js
/tmp/node-checker.git/lib/index.js
/tmp/node-checker.git/lib/health_checker.js
/tmp/node-checker.git/lib/checkers/noop_checker.js
/tmp/node-checker.git/lib/checkers/dns_checker.js
/tmp/node-checker.git/lib/checkers/http_checker.js
/tmp/node-checker.git/lib/checkers/tcp_checker.js
/tmp/node-checker.git/lib/checkers/checker.js
/tmp/node-checker.git/lib/all_checkers.js
/tmp/node-checker.git/lib/hc_server.js
/tmp/node-checker.git/lib/time_bucket.js
/home/timf/projects/manta-madtom.git/build/node/bin/node /home/timf/projects/manta-madtom.git/build/node/bin/npm install json
npm WARN package.json checker@1.0.0 No repository field.
json@9.0.6 node_modules/json
node_modules/.bin/json --validate -f package.json
deps/jsstyle/jsstyle -f tools/jsstyle.conf lib/index.js lib/health_checker.js lib/checkers/noop_checker.js lib/checkers/dns_checker.js lib/checkers/http_checker.js lib/checkers/tcp_checker.js lib/checkers/checker.js lib/all_checkers.js lib/hc_server.js lib/time_bucket.js
check ok
/home/timf/projects/manta-madtom.git/build/node/bin/node /home/timf/projects/manta-madtom.git/build/node/bin/npm install
npm WARN package.json checker@1.0.0 No repository field.
npm WARN deprecated connect@2.6.2: connect 2.x series is deprecated

> dtrace-provider@0.2.4 install /tmp/node-checker.git/node_modules/bunyan/node_modules/dtrace-provider
> node-gyp rebuild

make[1]: Entering directory `/tmp/node-checker.git/node_modules/bunyan/node_modules/dtrace-provider/build'
  LD_LIBRARY_PATH=/tmp/node-checker.git/node_modules/bunyan/node_modules/dtrace-provider/build/Release/lib.host:/tmp/node-checker.git/node_modules/bunyan/node_modules/dtrace-provider/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; sh libusdt-build.sh
Using node: /home/timf/projects/manta-madtom.git/build/node/bin/node
Building libusdt for i386
make[2]: Entering directory `/tmp/node-checker.git/node_modules/bunyan/node_modules/dtrace-provider/libusdt'
rm -f *.gch
rm -f *.o
rm -f libusdt.a
rm -f test_usdt
rm -f test_usdt32
rm -f test_usdt64
gcc -O2 -fPIC   -c -o usdt.o usdt.c
gcc -O2 -fPIC   -c -o usdt_dof_file.o usdt_dof_file.c
gcc -O2 -fPIC -o usdt_tracepoints.o -c usdt_tracepoints_i386.s
gcc -O2 -fPIC   -c -o usdt_probe.o usdt_probe.c
gcc -O2 -fPIC   -c -o usdt_dof.o usdt_dof.c
gcc -O2 -fPIC   -c -o usdt_dof_sections.o usdt_dof_sections.c
rm -f libusdt.a
ar cru libusdt.a usdt.o usdt_dof_file.o usdt_tracepoints.o usdt_probe.o usdt_dof.o usdt_dof_sections.o
/bin/true libusdt.a
make[2]: Leaving directory `/tmp/node-checker.git/node_modules/bunyan/node_modules/dtrace-provider/libusdt'
  touch Release/obj.target/libusdt.stamp
  g++ '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/tmp/a/.node-gyp/0.10.32/src -I/tmp/a/.node-gyp/0.10.32/deps/uv/include -I/tmp/a/.node-gyp/0.10.32/deps/v8/include -I../libusdt  -fPIC -Wall -Wextra -Wno-unused-parameter -m32 -pthreads -O2 -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF ./Release/.deps/Release/obj.target/DTraceProviderBindings/dtrace_provider.o.d.raw  -c -o Release/obj.target/DTraceProviderBindings/dtrace_provider.o ../dtrace_provider.cc
  g++ '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/tmp/a/.node-gyp/0.10.32/src -I/tmp/a/.node-gyp/0.10.32/deps/uv/include -I/tmp/a/.node-gyp/0.10.32/deps/v8/include -I../libusdt  -fPIC -Wall -Wextra -Wno-unused-parameter -m32 -pthreads -O2 -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF ./Release/.deps/Release/obj.target/DTraceProviderBindings/dtrace_probe.o.d.raw  -c -o Release/obj.target/DTraceProviderBindings/dtrace_probe.o ../dtrace_probe.cc
  ./gyp-flock-tool flock ./Release/linker.lock g++ -shared -rdynamic -m32 -pthreads -Wl,-z,allextract  -Wl,-soname=DTraceProviderBindings.node -o Release/obj.target/DTraceProviderBindings.node -Wl,--start-group Release/obj.target/DTraceProviderBindings/dtrace_provider.o Release/obj.target/DTraceProviderBindings/dtrace_probe.o -Wl,--end-group -L/tmp/node-checker.git/node_modules/bunyan/node_modules/dtrace-provider/libusdt -l usdt
  SOLINK_MODULE(target) Release/obj.target/DTraceProviderBindings.node: Finished
  rm -rf "Release/DTraceProviderBindings.node" && cp -af "Release/obj.target/DTraceProviderBindings.node" "Release/DTraceProviderBindings.node"
make[1]: Leaving directory `/tmp/node-checker.git/node_modules/bunyan/node_modules/dtrace-provider/build'
assert-plus@0.1.1 node_modules/assert-plus

posix-getopt@1.0.0 node_modules/posix-getopt

nodeunit@0.7.4 node_modules/nodeunit

vasync@1.3.3 node_modules/vasync
├── verror@1.1.0 (extsprintf@1.0.0)
└── jsprim@0.3.0 (extsprintf@1.0.0, verror@1.3.3, json-schema@0.2.2)

native-dns@0.4.1 node_modules/native-dns
├── binaryheap@0.0.3
├── ipaddr.js@1.9.1
└── buffercursor@0.0.12 (verror@1.10.0)

express@3.0.1 node_modules/express
├── methods@0.0.1
├── fresh@0.1.0
├── cookie-signature@0.0.1
├── range-parser@0.0.4
├── cookie@0.0.4
├── crc@0.2.0
├── commander@0.6.1
├── mkdirp@0.3.3
├── send@0.1.0 (mime@1.2.6)
├── debug@4.1.1 (ms@2.1.2)
└── connect@2.6.2 (pause@0.0.1, bytes@0.1.0, formidable@1.0.11, qs@0.5.1)

tap@0.2.3 node_modules/tap
├── deep-equal@0.0.0
├── slide@1.1.6
├── mkdirp@0.2.2
├── nopt@1.0.10 (abbrev@1.1.1)
├── difflet@0.2.0 (charm@0.0.8, traverse@0.6.6)
└── runforcover@0.0.2 (bunker@0.1.2)

bunyan@0.16.6 node_modules/bunyan
└── dtrace-provider@0.2.4
find test/ -name '*.test.js' | xargs -t -L1 ./node_modules/.bin/nodeunit
./node_modules/.bin/nodeunit test/health_checker.test.js

health_checker.test.js
{"name":"checker","hostname":"jenkins-agent-i386-1.6.3","pid":58590,"level":30,"hostType":"test","ip":"127.0.0.1","uuid":"111-111-1111","datacenter":"local","server":"127.0.0.1","processType":"test","id":1,"checkerType":"testChecker","stats":{"lastChecked":1572278219892,"lastLatency":0,"healthy":true,"success":true},"msg":"audit","time":"2019-10-28T15:56:59.893Z","v":0}
{"name":"checker","hostname":"jenkins-agent-i386-1.6.3","pid":58590,"level":30,"hostType":"test","ip":"127.0.0.1","uuid":"111-111-1111","datacenter":"local","server":"127.0.0.1","processType":"test","id":2,"checkerType":"testChecker","stats":{"lastChecked":1572278219894,"lastLatency":0,"healthy":true,"success":true},"msg":"audit","time":"2019-10-28T15:56:59.894Z","v":0}
{"name":"checker","hostname":"jenkins-agent-i386-1.6.3","pid":58590,"level":30,"msg":"Stopping health checker","time":"2019-10-28T15:57:10.893Z","v":0}
{"name":"checker","hostname":"jenkins-agent-i386-1.6.3","pid":58590,"level":30,"cfg":{"hostType":"test","ip":"127.0.0.1","uuid":"111-111-1111","datacenter":"local","server":"127.0.0.1","processType":"test","id":1,"checkerType":"testChecker"},"msg":"stopping checker","time":"2019-10-28T15:57:10.893Z","v":0}
{"name":"checker","hostname":"jenkins-agent-i386-1.6.3","pid":58590,"level":30,"cfg":{"hostType":"test","ip":"127.0.0.1","uuid":"111-111-1111","datacenter":"local","server":"127.0.0.1","processType":"test","id":2,"checkerType":"testChecker"},"msg":"stopping checker","time":"2019-10-28T15:57:10.894Z","v":0}
✔ the checks we configure execute and count up

OK: 3 assertions (11028ms)
./node_modules/.bin/nodeunit test/http_checker.test.js

/tmp/node-checker.git/node_modules/express/node_modules/debug/src/node.js:120
exports.inspectOpts = Object.keys(process.env).filter(key => {
                                                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/tmp/node-checker.git/node_modules/express/node_modules/debug/src/index.js:9:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
./node_modules/.bin/nodeunit test/time_bucket.test.js

time_bucket.test.js
✔ simple bucket
✔ simple bucket, bools
✔ add outside time period
✔ period roll over

OK: 46 assertions (2027ms)
make: *** [test] Error 123
```

In this case, `express` has this dependency on `debug`:

```
"debug": "*"
```

Maybe we could try forcing that back to some older compatible node, but I'm losing the will..

**Comment by trentm** [comment]
@timfoster I had to fix "TOOLS-2101 jsstyle submodules too old for old perls" as well. Ready for review when you get a chance. Thanks.

**Comment by timfoster** [comment]
I thought I did already?

**Comment by trentm** [comment]
> I thought I did already?

New commits invalidate earlier approvals. At least that's how we've configured our branch protection for "master":

Screenshot 2019-10-28 11 24 03

This, IIUC, is the equivalent of how CR/IA-removal on new patchsets worked with our Gerrit.

**Pull request merged**
